# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Base' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
use_frameworks!

  # Pods for Base

  target 'BaseTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'BaseUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end


pod "AFNetworking"
pod 'SDWebImage'
pod 'MJRefresh'
pod 'MJExtension'
pod 'Masonry'
pod 'MBProgressHUD'